# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f6d3ff23c78304770212ab63c742fbee0c205264597c6a8e84d99d6ec776584d40c5bedcd08020b1c9addf1f6c7347834d7479ea5fa3f991b0009eda17651b2

test:
  secret_key_base: 716286672e1f05a2718382ffaa08ebe58845894a5a59adc1f0e8f4e8374334d2ceb582da8e4206b2cfa4acecf9613116b29a53f2a91d03f9b5079bc631f19acb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
